### ISSUE TITLE
Error while fetching data

### ISSUE THREAD

**Issue by ghost** [wavesplatform/blockchain-postgres-sync#4]
venom@p0ison:~/blockchain-postgres-sync$ npm run download 1 1000

> blockchain-postgres-sync@0.2.0 download /home/venom/blockchain-postgres-sync
> node src/runForRange.js "1" "1000"

Requesting blocks: 325.149ms
1 — 100 insert, 100 objects: 148.768ms
Requesting blocks: 412.905ms
101 — 200 insert, 100 objects: 70.735ms

/home/venom/blockchain-postgres-sync/node_modules/json-bigint/lib/parse.js:112
            throw {
            ^
SyntaxError: Unexpected '<'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockchain-postgres-sync@0.2.0 download: `node src/runForRange.js "1" "1000"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-postgres-sync@0.2.0 download script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/venom/.npm/_logs/2018-09-22T23_35_31_987Z-debug.log

**Comment by deepred86** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'download', '1', '1000' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'predownload', 'download', 'postdownload' ]
5 info lifecycle blockchain-postgres-sync@0.2.0~predownload: blockchain-postgres-sync@0.2.0
6 info lifecycle blockchain-postgres-sync@0.2.0~download: blockchain-postgres-sync@0.2.0
7 verbose lifecycle blockchain-postgres-sync@0.2.0~download: unsafe-perm in lifecycle true
8 verbose lifecycle blockchain-postgres-sync@0.2.0~download: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/venom/blockchain-postg$
9 verbose lifecycle blockchain-postgres-sync@0.2.0~download: CWD: /home/venom/blockchain-postgres-sync
10 silly lifecycle blockchain-postgres-sync@0.2.0~download: Args: [ '-c', 'node src/runForRange.js "1" "1000"' ]
11 silly lifecycle blockchain-postgres-sync@0.2.0~download: Returned: code: 1  signal: null
12 info lifecycle blockchain-postgres-sync@0.2.0~download: Failed to exec download script
13 verbose stack Error: blockchain-postgres-sync@0.2.0 download: `node src/runForRange.js "1" "1000"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid blockchain-postgres-sync@0.2.0
15 verbose cwd /home/deepred/blockchain-postgres-sync
16 verbose Linux 4.15.0-34-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "download" "1" "1000"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error blockchain-postgres-sync@0.2.0 download: `node src/runForRange.js "1" "1000"`
22 error Exit status 1
23 error Failed at the blockchain-postgres-sync@0.2.0 download script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dvshur** [comment]
Hi, @deepred86, thank you for using our scripts and providing feedback.

The reason for error `SyntaxError: Unexpected '<'` is, most likely, that the server response was not a valid JSON, but an HTML page instead (starting with the tag `<html>`, hence the leading `<`). This can happen in case of the server being down/returning a 5xx error.

You could try decreasing the number of blocks per request as it makes it easier on the backend node, lowering chance of encountering errors. Also, if you encounter a specific problematic range (big blocks, for example), consider splitting it into shorter ranges of 10k/50k blocks to save each small range independently.
