### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fabiomattes2016** [wavesplatform/blockchain-postgres-sync#9]
command: npm run download 0 100000

error: 
SequenceError {
    message: "relation \"blocks_raw\" does not exist"
    reason: Source <anonymous> returned a rejection at index 0.
    index: 0
    duration: 1723
    error: { error: relation "blocks_raw" does not exist
        at Connection.parseE (D:\blockchain-postgres-sync\node_modules\pg\lib\connection.js:545:11)
        at Connection.parseMessage (D:\blockchain-postgres-sync\node_modules\pg\lib\connection.js:370:19)
        at Socket.<anonymous> (D:\blockchain-postgres-sync\node_modules\pg\lib\connection.js:113:22)
        at Socket.emit (events.js:189:13)
        at addChunk (_stream_readable.js:284:12)
        at readableAddChunk (_stream_readable.js:265:11)
        at Socket.Readable.push (_stream_readable.js:220:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
      name: 'error',
      length: 102,
      severity: 'ERROR',
      code: '42P01',
      detail: undefined,
      hint: undefined,
      position: '13',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '1160',
      routine: 'parserOpenTable' }
}

**Comment by fabiomattes2016** [comment]
> command: npm run download 0 100000
> 
> error:
> SequenceError {
> message: "relation "blocks_raw" does not exist"
> reason: Source returned a rejection at index 0.
> index: 0
> duration: 1723
> error: { error: relation "blocks_raw" does not exist
> at Connection.parseE (D:\blockchain-postgres-sync\node_modules\pg\lib\connection.js:545:11)
> at Connection.parseMessage (D:\blockchain-postgres-sync\node_modules\pg\lib\connection.js:370:19)
> at Socket. (D:\blockchain-postgres-sync\node_modules\pg\lib\connection.js:113:22)
> at Socket.emit (events.js:189:13)
> at addChunk (_stream_readable.js:284:12)
> at readableAddChunk (_stream_readable.js:265:11)
> at Socket.Readable.push (_stream_readable.js:220:10)
> at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> name: 'error',
> length: 102,
> severity: 'ERROR',
> code: '42P01',
> detail: undefined,
> hint: undefined,
> position: '13',
> internalPosition: undefined,
> internalQuery: undefined,
> where: undefined,
> schema: undefined,
> table: undefined,
> column: undefined,
> dataType: undefined,
> constraint: undefined,
> file: 'parse_relation.c',
> line: '1160',
> routine: 'parserOpenTable' }
> }

I forgot the schema script

**Comment by dvshur** [comment]
Glad you solved it :) Closing

**Comment by narmathamuthu** [comment]
@dvshur 

I got error when i am run the migrate command ( npm run migrate -- --connection postgresql://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$DB ) . 

PFA.

![Screenshot from 2019-10-21 14-50-54](https://user-images.githubusercontent.com/55826071/67193001-3195cb80-f412-11e9-8370-a25e3b3f85ff.png)

Can you please explain me.
